spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ingestion-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8085
        specific.avro.reader: false

  datasource:
    url: jdbc:postgresql://localhost:5432/incidentdb
    username: naja
    password: naja123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8082

